name: "Test CI"

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check for flake configurations
        run: nix flake check --all-systems --show-trace

      - name: Build the project
        run: nix-shell --run "cargo build --release --verbose"

      - name: Run lint
        run: nix-shell --run "cargo clippy --verbose"

      - name: Run format check
        run: nix-shell --run "cargo fmt --all -- --check"

      - name: Run tests
        run: nix-shell --run "cargo test --verbose"

      - name: Build nix package
        run: nix build .
